---
# glusterfs_servers/tasks/configure_glusterfs.yml

- name: 'Create directories /gluster/ and /glusterfs/'
  file:
    path: "{{ item }}"
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0775'
  with_items:
    - '/gluster/'
    - '/glusterfs/'

- name: 'Start service'
  service:
    name: "{{ glusterfs_server_service }}"
    state: 'started'
    enabled: 'true'
