---
# glusterfs_servers/tasks/main.yml

- name: "Load variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "vars_{{ ansible_distribution }}.yml"
    - "vars_{{ ansible_os_family }}.yml"

- name: 'Install packages'
  ansible.builtin.include_tasks: install_packages.yml

- name: 'Configure glusterfs'
  ansible.builtin.include_tasks: configure_glusterfs.yml

- name: 'Prepare file with instructions on how to setup the cluster'
  ansible.builtin.include_tasks: create_file_with_instructions.yml
