---
# glusterfs_servers/tasks/main.yml

- name: "Load variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars_{{ ansible_distribution }}.yml"
    - "vars_{{ ansible_os_family }}.yml"

- name: 'Install packages'
  include_tasks: install_packages.yml

- name: 'Add storage network names to /etc/hosts'
  include_tasks: add_storage_network_names_to_etc_hosts.yml

- name: 'Configure glusterfs'
  include_tasks: configure_glusterfs.yml
