---
# glusterfs_servers/tasks/main.yml

- name: "Load variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "vars_{{ ansible_distribution }}.yml"
    - "vars_{{ ansible_os_family }}.yml"

- name: 'Install packages'
  ansible.builtin.include_tasks: install_packages.yml

- name: 'Configure glusterfs'
  ansible.builtin.include_tasks: configure_glusterfs.yml

- name: 'Prepare file with instructions on how to setup the cluster'
  ansible.builtin.include_tasks: create_file_with_instructions.yml

- name: 'Force usage of IPv4, if no IPv6 is present'
  ansible.builtin.lineinfile:
    path: '/etc/glusterfs/glusterd.vol'
    regexp: 'option transport.address-family'
    line: '    option transport.address-family inet'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Restart the glusterd service'
  when:
    - 'force_ipv4_as_ipv6_not_available is defined'
    - 'force_ipv4_as_ipv6_not_available | bool'
